### ISSUE TITLE
Project seems popular ... README help => more popular?

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/aws-saml-login#6]
Good stats on PyPi, and thinking that with a bit more explanation it could help push the project further. LMK! Henning, we might need to create a priorities list -- you have a great/impressive body of work. :)

**Comment by lasomethingsomething** [comment]
@hjacobs @tuxlife Checking in here--guys?

**Comment by hjacobs** [comment]
@LappleApple not sure how popular this really is, it's quite a niche: federated AWS login is mostly/only used by bigger companies/enterprises and this library only works with Python and the Open Source Shibboleth IDP (http://shibboleth.net/).

**Comment by lasomethingsomething** [comment]
@hjacobs Could be a niche, but if it's an important niche then it's a useful project. :) We can try to polish it up a bit and see what happens -- I'm willing to do some README work on it and push it/promote it to see if it gains traction. Would there be any reason to reach out to the Shibboleth crew?
